antora:
  extensions:
    - '@antora/lunr-extension'
    # - '@antora/pdf-extension'
    
site:
  title: Antora Docs
  start_page: github-pages-test::index.adoc 
content:
  sources: 
  - url: https://github.com/Change-Financial/gh-pages-test
    branches: HEAD
    start_path: docs
ui: 
  bundle:
    url: ui-bundle.zip
    snapshot: true